package hibpck;
// Generated Oct 17, 2013 4:56:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ContainerType generated by hbm2java
 */
public class ContainerType  implements java.io.Serializable {


     private Integer idcontainerType;
     private String typeName;
     private Set<Container> containers = new HashSet<Container>(0);

    public ContainerType() {
    }

    public ContainerType(String typeName, Set<Container> containers) {
       this.typeName = typeName;
       this.containers = containers;
    }
   
    public Integer getIdcontainerType() {
        return this.idcontainerType;
    }
    
    public void setIdcontainerType(Integer idcontainerType) {
        this.idcontainerType = idcontainerType;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Set<Container> getContainers() {
        return this.containers;
    }
    
    public void setContainers(Set<Container> containers) {
        this.containers = containers;
    }




}


