package hibpck;
// Generated Oct 17, 2013 4:56:36 PM by Hibernate Tools 3.2.1.GA



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private Integer idimage;
     private Products products;
     private byte[] image;

    public Image() {
    }

	
    public Image(Products products) {
        this.products = products;
    }
    public Image(Products products, byte[] image) {
       this.products = products;
       this.image = image;
    }
   
    public Integer getIdimage() {
        return this.idimage;
    }
    
    public void setIdimage(Integer idimage) {
        this.idimage = idimage;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


