package hibpck;
// Generated Oct 17, 2013 4:56:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ProductInContainer generated by hbm2java
 */
public class ProductInContainer  implements java.io.Serializable {


     private int idpc;
     private Container container;
     private SystemStatus systemStatus;
     private Products products;
     private Double qty;
     private Double amount;
     private Date addedDate;

    public ProductInContainer() {
    }

	
    public ProductInContainer(int idpc, Container container, SystemStatus systemStatus, Products products) {
        this.idpc = idpc;
        this.container = container;
        this.systemStatus = systemStatus;
        this.products = products;
    }
    public ProductInContainer(int idpc, Container container, SystemStatus systemStatus, Products products, Double qty, Double amount, Date addedDate) {
       this.idpc = idpc;
       this.container = container;
       this.systemStatus = systemStatus;
       this.products = products;
       this.qty = qty;
       this.amount = amount;
       this.addedDate = addedDate;
    }
   
    public int getIdpc() {
        return this.idpc;
    }
    
    public void setIdpc(int idpc) {
        this.idpc = idpc;
    }
    public Container getContainer() {
        return this.container;
    }
    
    public void setContainer(Container container) {
        this.container = container;
    }
    public SystemStatus getSystemStatus() {
        return this.systemStatus;
    }
    
    public void setSystemStatus(SystemStatus systemStatus) {
        this.systemStatus = systemStatus;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }




}


