package hibpck;
// Generated Oct 17, 2013 4:56:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ProductType generated by hbm2java
 */
public class ProductType  implements java.io.Serializable {


     private Integer idproductType;
     private String typeName;
     private Set<Products> productses = new HashSet<Products>(0);

    public ProductType() {
    }

    public ProductType(String typeName, Set<Products> productses) {
       this.typeName = typeName;
       this.productses = productses;
    }
   
    public Integer getIdproductType() {
        return this.idproductType;
    }
    
    public void setIdproductType(Integer idproductType) {
        this.idproductType = idproductType;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


