package hibpck;
// Generated Oct 17, 2013 4:56:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer idproducts;
     private User user;
     private ProductType productType;
     private String productName;
     private Double qty;
     private Double unitPrice;
     private Date registerDate;
     private Set<ProductInContainer> productInContainers = new HashSet<ProductInContainer>(0);
     private Set<Image> images = new HashSet<Image>(0);

    public Products() {
    }

	
    public Products(User user, ProductType productType) {
        this.user = user;
        this.productType = productType;
    }
    public Products(User user, ProductType productType, String productName, Double qty, Double unitPrice, Date registerDate, Set<ProductInContainer> productInContainers, Set<Image> images) {
       this.user = user;
       this.productType = productType;
       this.productName = productName;
       this.qty = qty;
       this.unitPrice = unitPrice;
       this.registerDate = registerDate;
       this.productInContainers = productInContainers;
       this.images = images;
    }
   
    public Integer getIdproducts() {
        return this.idproducts;
    }
    
    public void setIdproducts(Integer idproducts) {
        this.idproducts = idproducts;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public ProductType getProductType() {
        return this.productType;
    }
    
    public void setProductType(ProductType productType) {
        this.productType = productType;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Date getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
    public Set<ProductInContainer> getProductInContainers() {
        return this.productInContainers;
    }
    
    public void setProductInContainers(Set<ProductInContainer> productInContainers) {
        this.productInContainers = productInContainers;
    }
    public Set<Image> getImages() {
        return this.images;
    }
    
    public void setImages(Set<Image> images) {
        this.images = images;
    }




}


