package hibpck;
// Generated Oct 17, 2013 4:56:36 PM by Hibernate Tools 3.2.1.GA



/**
 * SessionActivities generated by hbm2java
 */
public class SessionActivities  implements java.io.Serializable {


     private Integer idsessionActivities;
     private LoginSession loginSession;
     private String activity;

    public SessionActivities() {
    }

	
    public SessionActivities(LoginSession loginSession) {
        this.loginSession = loginSession;
    }
    public SessionActivities(LoginSession loginSession, String activity) {
       this.loginSession = loginSession;
       this.activity = activity;
    }
   
    public Integer getIdsessionActivities() {
        return this.idsessionActivities;
    }
    
    public void setIdsessionActivities(Integer idsessionActivities) {
        this.idsessionActivities = idsessionActivities;
    }
    public LoginSession getLoginSession() {
        return this.loginSession;
    }
    
    public void setLoginSession(LoginSession loginSession) {
        this.loginSession = loginSession;
    }
    public String getActivity() {
        return this.activity;
    }
    
    public void setActivity(String activity) {
        this.activity = activity;
    }




}


