package hibpck;
// Generated Oct 17, 2013 4:56:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SystemStatus generated by hbm2java
 */
public class SystemStatus  implements java.io.Serializable {


     private Integer idsystemStatus;
     private String statusName;
     private Set<User> users = new HashSet<User>(0);
     private Set<ProductInContainer> productInContainers = new HashSet<ProductInContainer>(0);
     private Set<UserLogin> userLogins = new HashSet<UserLogin>(0);

    public SystemStatus() {
    }

    public SystemStatus(String statusName, Set<User> users, Set<ProductInContainer> productInContainers, Set<UserLogin> userLogins) {
       this.statusName = statusName;
       this.users = users;
       this.productInContainers = productInContainers;
       this.userLogins = userLogins;
    }
   
    public Integer getIdsystemStatus() {
        return this.idsystemStatus;
    }
    
    public void setIdsystemStatus(Integer idsystemStatus) {
        this.idsystemStatus = idsystemStatus;
    }
    public String getStatusName() {
        return this.statusName;
    }
    
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<ProductInContainer> getProductInContainers() {
        return this.productInContainers;
    }
    
    public void setProductInContainers(Set<ProductInContainer> productInContainers) {
        this.productInContainers = productInContainers;
    }
    public Set<UserLogin> getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }




}


