package hibpck;
// Generated Oct 17, 2013 4:56:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private SystemStatus systemStatus;
     private UserType userType;
     private String firstName;
     private String lastName;
     private String address;
     private String city;
     private String state;
     private String pinCode;
     private String country;
     private String tel;
     private Set<UserLogin> userLogins = new HashSet<UserLogin>(0);
     private Set<Container> containers = new HashSet<Container>(0);
     private Set<Products> productses = new HashSet<Products>(0);

    public User() {
    }

	
    public User(SystemStatus systemStatus, UserType userType) {
        this.systemStatus = systemStatus;
        this.userType = userType;
    }
    public User(SystemStatus systemStatus, UserType userType, String firstName, String lastName, String address, String city, String state, String pinCode, String country, String tel, Set<UserLogin> userLogins, Set<Container> containers, Set<Products> productses) {
       this.systemStatus = systemStatus;
       this.userType = userType;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.city = city;
       this.state = state;
       this.pinCode = pinCode;
       this.country = country;
       this.tel = tel;
       this.userLogins = userLogins;
       this.containers = containers;
       this.productses = productses;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public SystemStatus getSystemStatus() {
        return this.systemStatus;
    }
    
    public void setSystemStatus(SystemStatus systemStatus) {
        this.systemStatus = systemStatus;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getPinCode() {
        return this.pinCode;
    }
    
    public void setPinCode(String pinCode) {
        this.pinCode = pinCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public Set<UserLogin> getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }
    public Set<Container> getContainers() {
        return this.containers;
    }
    
    public void setContainers(Set<Container> containers) {
        this.containers = containers;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


